//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NikSoft.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NikSoft {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public NikSoft() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NikSoft.Utilities.NikSoft", typeof(NikSoft).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to گروه نیک نرم افزار.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اتوماسیون.
        /// </summary>
        public static string NavLink_Automation {
            get {
                return ResourceManager.GetString("NavLink_Automation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string NavLink_Email {
            get {
                return ResourceManager.GetString("NavLink_Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شبکه.
        /// </summary>
        public static string NavLink_Interanet {
            get {
                return ResourceManager.GetString("NavLink_Interanet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to انتخاب کنید.
        /// </summary>
        public static string Portal_Select {
            get {
                return ResourceManager.GetString("Portal_Select", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search_PlaceHolder {
            get {
                return ResourceManager.GetString("Search_PlaceHolder", resourceCulture);
            }
        }
    }
}
